### ISSUE TITLE
Allow .chukfile in HOME directory of user

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/chuk#6]
If user has a chukfile in his HOME directory, this is always loaded

Problem is where to put libraries which are used there?

**Comment by behrendtio** [comment]
Isn't a `Chukfile` project specific anyway? This will not work smoothly with npm modules, as you mentioned.

**Comment by StephanHoyer** [comment]
The idea is if one user has his special helpers she always uses, she can make them available in the REPL.

**Comment by behrendtio** [comment]
Well at the end the user is responsible for what he's putting into the `Chukfile`. So if the modules can't be found, `chuk` shouldn't care. So fine with me :)

**Comment by StephanHoyer** [comment]
https://trello.com/c/CO5IppjZ
