### ISSUE TITLE
Modify REPL History

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/chuk#8]
Maybe it would be cool to store command history and apply it once chuk is started again. Or add same history the user added somewhere to the history every time chuk is used?

**Comment by behrendtio** [comment]
We could do something like [this](https://github.com/tmpvar/repl.history/blob/master/index.js). I don't like his implementation, but at the end of the day, the result should look similar. Don't you think?

**Comment by StephanHoyer** [comment]
Yep. Just like this. Maybe project specific

**Comment by StephanHoyer** [comment]
https://trello.com/c/A1PO00k3
